SELECT
    *
FROM
    TEST.DEMO_CUSTOMERS
    INNER JOIN "TEST"."DEMO_ORDERS" ON "DEMO_CUSTOMERS"."CUSTOMER_ID" = "DEMO_ORDERS"."CUSTOMER_ID"
    WHERE
        "DEMO_CUSTOMERS"."CUST_FIRST_NAME" = 'Eugene';